# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.0.3
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: PIP
generate_requirements_txt: false
include_wkhtmltopdf: false
odoo_version: 13.0
rebel_module_groups: []
repo_description: Website addons for Odoo
repo_name: Website addons for Odoo
repo_slug: glodouk/website
travis_apt_packages: []
travis_apt_sources: []
