{
    "name": "website_leaflet",
    "summary": "Adds a leaflet.js powered map (eventually snippet)",
    "author": "Glodo",
    "website": "https://www.glodo.uk/",
    "category": "Hidden",
    "version": "13.0.1.0.0",
    "depends": ["website"],
    "external_dependencies": {"python": []},
    "data": ["templates/assets.xml"],
    "demo": [],
    "installable": True,
    "application": False,
    "license": "AGPL-3",
}
